// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"github.com/aisk/goblin/token"
)

const (
	NoState    = -1
	NumStates  = 78
	NumSymbols = 85
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '.'
1: '"'
2: '"'
3: '&'
4: '&'
5: '|'
6: '|'
7: '+'
8: '-'
9: '*'
10: '/'
11: '!'
12: '('
13: ')'
14: 't'
15: 'r'
16: 'u'
17: 'e'
18: 'f'
19: 'a'
20: 'l'
21: 's'
22: 'e'
23: 'n'
24: 'i'
25: 'l'
26: '['
27: ']'
28: ','
29: 'v'
30: 'a'
31: 'r'
32: '='
33: '{'
34: '}'
35: 'i'
36: 'f'
37: 'e'
38: 'l'
39: 's'
40: 'e'
41: 'w'
42: 'h'
43: 'i'
44: 'l'
45: 'e'
46: 'f'
47: 'o'
48: 'r'
49: 'i'
50: 'n'
51: 'b'
52: 'r'
53: 'e'
54: 'a'
55: 'k'
56: 'f'
57: 'u'
58: 'n'
59: 'c'
60: 'r'
61: 'e'
62: 't'
63: 'u'
64: 'r'
65: 'n'
66: '_'
67: '\'
68: '"'
69: '\'
70: ' '
71: '\t'
72: '\n'
73: '\r'
74: '#'
75: '\n'
76: '0'-'9'
77: 'a'-'z'
78: 'A'-'Z'
79: \u0001-'!'
80: '#'-'['
81: ']'-\u007f
82: \u0080-\ufffc
83: \ufffe-\U0010ffff
84: .
*/
