// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"github.com/aisk/goblin/token"
)

const (
	NoState    = -1
	NumStates  = 108
	NumSymbols = 123
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '.'
1: '"'
2: '"'
3: '['
4: ']'
5: '('
6: ')'
7: '.'
8: 'i'
9: 'm'
10: 'p'
11: 'o'
12: 'r'
13: 't'
14: '&'
15: '&'
16: '|'
17: '|'
18: '='
19: '='
20: '!'
21: '='
22: '<'
23: '='
24: '>'
25: '='
26: '<'
27: '>'
28: '+'
29: '-'
30: '*'
31: '/'
32: '!'
33: 'f'
34: 'u'
35: 'n'
36: 'c'
37: 't'
38: 'r'
39: 'u'
40: 'e'
41: 'f'
42: 'a'
43: 'l'
44: 's'
45: 'e'
46: 'n'
47: 'i'
48: 'l'
49: ','
50: '{'
51: '}'
52: ':'
53: '='
54: '*'
55: '*'
56: 'v'
57: 'a'
58: 'r'
59: 'i'
60: 'f'
61: 'e'
62: 'l'
63: 's'
64: 'e'
65: 'w'
66: 'h'
67: 'i'
68: 'l'
69: 'e'
70: 'f'
71: 'o'
72: 'r'
73: 'i'
74: 'n'
75: 'b'
76: 'r'
77: 'e'
78: 'a'
79: 'k'
80: 'c'
81: 'o'
82: 'n'
83: 't'
84: 'i'
85: 'n'
86: 'u'
87: 'e'
88: 't'
89: 'y'
90: 'p'
91: 'e'
92: 'r'
93: 'e'
94: 't'
95: 'u'
96: 'r'
97: 'n'
98: 'e'
99: 'x'
100: 'p'
101: 'o'
102: 'r'
103: 't'
104: '_'
105: '\'
106: '"'
107: '\'
108: ' '
109: '\t'
110: '\n'
111: '\r'
112: '#'
113: '\n'
114: '0'-'9'
115: 'a'-'z'
116: 'A'-'Z'
117: \u0001-'!'
118: '#'-'['
119: ']'-\u007f
120: \u0080-\ufffc
121: \ufffe-\U0010ffff
122: .
*/
