// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"github.com/aisk/goblin/token"
)

const (
	NoState    = -1
	NumStates  = 68
	NumSymbols = 76
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '"'
1: '"'
2: '+'
3: '-'
4: '*'
5: '/'
6: '!'
7: '('
8: ')'
9: 't'
10: 'r'
11: 'u'
12: 'e'
13: 'f'
14: 'a'
15: 'l'
16: 's'
17: 'e'
18: 'n'
19: 'i'
20: 'l'
21: ','
22: 'v'
23: 'a'
24: 'r'
25: '='
26: '{'
27: '}'
28: 'i'
29: 'f'
30: 'e'
31: 'l'
32: 's'
33: 'e'
34: 'w'
35: 'h'
36: 'i'
37: 'l'
38: 'e'
39: 'b'
40: 'r'
41: 'e'
42: 'a'
43: 'k'
44: 'f'
45: 'u'
46: 'n'
47: 'c'
48: 'r'
49: 'e'
50: 't'
51: 'u'
52: 'r'
53: 'n'
54: '_'
55: '\'
56: '"'
57: '\'
58: ' '
59: '\t'
60: '\n'
61: '\r'
62: '/'
63: '*'
64: '*'
65: '*'
66: '/'
67: '0'-'9'
68: 'a'-'z'
69: 'A'-'Z'
70: \u0001-'!'
71: '#'-'['
72: ']'-\u007f
73: \u0080-\ufffc
74: \ufffe-\U0010ffff
75: .
*/
