// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 34: // ['"','"']
			return 2
		case r == 40: // ['(','(']
			return 3
		case r == 41: // [')',')']
			return 4
		case r == 44: // [',',',']
			return 5
		case r == 47: // ['/','/']
			return 6
		case 48 <= r && r <= 57: // ['0','9']
			return 7
		case 65 <= r && r <= 90: // ['A','Z']
			return 8
		case r == 95: // ['_','_']
			return 8
		case 97 <= r && r <= 122: // ['a','z']
			return 8
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 9
		case r == 34: // ['"','"']
			return 10
		case 35 <= r && r <= 91: // ['#','[']
			return 9
		case r == 92: // ['\','\']
			return 11
		case 93 <= r && r <= 127: // [']',\u007f]
			return 9
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 12
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 12
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 13
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 7
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 14
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 9
		case r == 34: // ['"','"']
			return 10
		case 35 <= r && r <= 91: // ['#','[']
			return 9
		case r == 92: // ['\','\']
			return 11
		case 93 <= r && r <= 127: // [']',\u007f]
			return 9
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 12
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 12
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 16
		case r == 34: // ['"','"']
			return 17
		case 35 <= r && r <= 91: // ['#','[']
			return 16
		case r == 92: // ['\','\']
			return 17
		case 93 <= r && r <= 127: // [']',\u007f]
			return 16
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 18
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 18
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 9
		case r == 34: // ['"','"']
			return 10
		case 35 <= r && r <= 91: // ['#','[']
			return 9
		case r == 92: // ['\','\']
			return 11
		case 93 <= r && r <= 127: // [']',\u007f]
			return 9
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 12
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 12
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 19
		default:
			return 13
		}
	},
	// S14
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 14
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 14
		case 65 <= r && r <= 90: // ['A','Z']
			return 15
		case r == 95: // ['_','_']
			return 15
		case 97 <= r && r <= 122: // ['a','z']
			return 15
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 9
		case r == 34: // ['"','"']
			return 10
		case 35 <= r && r <= 91: // ['#','[']
			return 9
		case r == 92: // ['\','\']
			return 11
		case 93 <= r && r <= 127: // [']',\u007f]
			return 9
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 12
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 12
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 9
		case r == 34: // ['"','"']
			return 10
		case 35 <= r && r <= 91: // ['#','[']
			return 9
		case r == 92: // ['\','\']
			return 11
		case 93 <= r && r <= 127: // [']',\u007f]
			return 9
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 12
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 12
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case 1 <= r && r <= 33: // [\u0001,'!']
			return 9
		case r == 34: // ['"','"']
			return 10
		case 35 <= r && r <= 91: // ['#','[']
			return 9
		case r == 92: // ['\','\']
			return 11
		case 93 <= r && r <= 127: // [']',\u007f]
			return 9
		case 128 <= r && r <= 65532: // [\u0080,\ufffc]
			return 12
		case 65534 <= r && r <= 1114111: // [\ufffe,\U0010ffff]
			return 12
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 19
		case r == 47: // ['/','/']
			return 20
		default:
			return 13
		}
	},
	// S20
	func(r rune) int {
		switch {
		}
		return NoState
	},
}
