// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: Statements
			nil,       // empty
			shift(10), // int_lit
			shift(11), // string_lit
			shift(12), // id
			nil,       // (
			nil,       // )
			nil,       // ,
			shift(13), // var
			nil,       // =
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // ␚
			nil,          // empty
			nil,          // int_lit
			nil,          // string_lit
			nil,          // id
			nil,          // (
			nil,          // )
			nil,          // ,
			nil,          // var
			nil,          // =
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // ␚, reduce: Module
			nil,       // empty
			nil,       // int_lit
			nil,       // string_lit
			nil,       // id
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // var
			nil,       // =
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // ␚, reduce: Statements
			nil,       // empty
			shift(10), // int_lit
			shift(11), // string_lit
			shift(12), // id
			nil,       // (
			nil,       // )
			nil,       // ,
			shift(13), // var
			nil,       // =
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // ␚, reduce: StatementList
			nil,       // empty
			reduce(4), // int_lit, reduce: StatementList
			reduce(4), // string_lit, reduce: StatementList
			reduce(4), // id, reduce: StatementList
			nil,       // (
			nil,       // )
			nil,       // ,
			reduce(4), // var, reduce: StatementList
			nil,       // =
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // ␚, reduce: Statement
			nil,       // empty
			reduce(6), // int_lit, reduce: Statement
			reduce(6), // string_lit, reduce: Statement
			reduce(6), // id, reduce: Statement
			nil,       // (
			nil,       // )
			nil,       // ,
			reduce(6), // var, reduce: Statement
			nil,       // =
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // ␚, reduce: Statement
			nil,       // empty
			reduce(7), // int_lit, reduce: Statement
			reduce(7), // string_lit, reduce: Statement
			reduce(7), // id, reduce: Statement
			nil,       // (
			nil,       // )
			nil,       // ,
			reduce(7), // var, reduce: Statement
			nil,       // =
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(12), // ␚, reduce: Expression
			nil,        // empty
			reduce(12), // int_lit, reduce: Expression
			reduce(12), // string_lit, reduce: Expression
			reduce(12), // id, reduce: Expression
			nil,        // (
			nil,        // )
			nil,        // ,
			reduce(12), // var, reduce: Expression
			nil,        // =
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(13), // ␚, reduce: Expression
			nil,        // empty
			reduce(13), // int_lit, reduce: Expression
			reduce(13), // string_lit, reduce: Expression
			reduce(13), // id, reduce: Expression
			nil,        // (
			nil,        // )
			nil,        // ,
			reduce(13), // var, reduce: Expression
			nil,        // =
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(14), // ␚, reduce: Expression
			nil,        // empty
			reduce(14), // int_lit, reduce: Expression
			reduce(14), // string_lit, reduce: Expression
			reduce(14), // id, reduce: Expression
			nil,        // (
			nil,        // )
			nil,        // ,
			reduce(14), // var, reduce: Expression
			nil,        // =
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(15), // ␚, reduce: IntegerLiteral
			nil,        // empty
			reduce(15), // int_lit, reduce: IntegerLiteral
			reduce(15), // string_lit, reduce: IntegerLiteral
			reduce(15), // id, reduce: IntegerLiteral
			nil,        // (
			nil,        // )
			nil,        // ,
			reduce(15), // var, reduce: IntegerLiteral
			nil,        // =
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(16), // ␚, reduce: StringLiteral
			nil,        // empty
			reduce(16), // int_lit, reduce: StringLiteral
			reduce(16), // string_lit, reduce: StringLiteral
			reduce(16), // id, reduce: StringLiteral
			nil,        // (
			nil,        // )
			nil,        // ,
			reduce(16), // var, reduce: StringLiteral
			nil,        // =
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // int_lit
			nil,       // string_lit
			nil,       // id
			shift(15), // (
			nil,       // )
			nil,       // ,
			nil,       // var
			nil,       // =
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // int_lit
			nil,       // string_lit
			shift(16), // id
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // var
			nil,       // =
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // ␚, reduce: StatementList
			nil,       // empty
			reduce(5), // int_lit, reduce: StatementList
			reduce(5), // string_lit, reduce: StatementList
			reduce(5), // id, reduce: StatementList
			nil,       // (
			nil,       // )
			nil,       // ,
			reduce(5), // var, reduce: StatementList
			nil,       // =
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			shift(21),  // int_lit
			shift(22),  // string_lit
			shift(23),  // id
			nil,        // (
			reduce(18), // ), reduce: Arguments
			nil,        // ,
			nil,        // var
			nil,        // =
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // int_lit
			nil,       // string_lit
			nil,       // id
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // var
			shift(26), // =
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // int_lit
			nil,        // string_lit
			nil,        // id
			nil,        // (
			reduce(20), // ), reduce: ArgumentList
			reduce(20), // ,, reduce: ArgumentList
			nil,        // var
			nil,        // =
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // int_lit
			nil,        // string_lit
			nil,        // id
			nil,        // (
			reduce(12), // ), reduce: Expression
			reduce(12), // ,, reduce: Expression
			nil,        // var
			nil,        // =
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // int_lit
			nil,        // string_lit
			nil,        // id
			nil,        // (
			reduce(13), // ), reduce: Expression
			reduce(13), // ,, reduce: Expression
			nil,        // var
			nil,        // =
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // int_lit
			nil,        // string_lit
			nil,        // id
			nil,        // (
			reduce(14), // ), reduce: Expression
			reduce(14), // ,, reduce: Expression
			nil,        // var
			nil,        // =
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // int_lit
			nil,        // string_lit
			nil,        // id
			nil,        // (
			reduce(15), // ), reduce: IntegerLiteral
			reduce(15), // ,, reduce: IntegerLiteral
			nil,        // var
			nil,        // =
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // int_lit
			nil,        // string_lit
			nil,        // id
			nil,        // (
			reduce(16), // ), reduce: StringLiteral
			reduce(16), // ,, reduce: StringLiteral
			nil,        // var
			nil,        // =
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // int_lit
			nil,       // string_lit
			nil,       // id
			shift(27), // (
			nil,       // )
			nil,       // ,
			nil,       // var
			nil,       // =
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // int_lit
			nil,       // string_lit
			nil,       // id
			nil,       // (
			shift(28), // )
			nil,       // ,
			nil,       // var
			nil,       // =
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // int_lit
			nil,        // string_lit
			nil,        // id
			nil,        // (
			reduce(19), // ), reduce: Arguments
			shift(29),  // ,
			nil,        // var
			nil,        // =
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(10), // int_lit
			shift(11), // string_lit
			shift(12), // id
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // var
			nil,       // =
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			shift(21),  // int_lit
			shift(22),  // string_lit
			shift(23),  // id
			nil,        // (
			reduce(18), // ), reduce: Arguments
			nil,        // ,
			nil,        // var
			nil,        // =
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(17), // ␚, reduce: FunctionCall
			nil,        // empty
			reduce(17), // int_lit, reduce: FunctionCall
			reduce(17), // string_lit, reduce: FunctionCall
			reduce(17), // id, reduce: FunctionCall
			nil,        // (
			nil,        // )
			nil,        // ,
			reduce(17), // var, reduce: FunctionCall
			nil,        // =
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(21), // int_lit
			shift(22), // string_lit
			shift(23), // id
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // var
			nil,       // =
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(22), // ␚, reduce: Declare
			nil,        // empty
			reduce(22), // int_lit, reduce: Declare
			reduce(22), // string_lit, reduce: Declare
			reduce(22), // id, reduce: Declare
			nil,        // (
			nil,        // )
			nil,        // ,
			reduce(22), // var, reduce: Declare
			nil,        // =
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // int_lit
			nil,       // string_lit
			nil,       // id
			nil,       // (
			shift(33), // )
			nil,       // ,
			nil,       // var
			nil,       // =
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // int_lit
			nil,        // string_lit
			nil,        // id
			nil,        // (
			reduce(21), // ), reduce: ArgumentList
			reduce(21), // ,, reduce: ArgumentList
			nil,        // var
			nil,        // =
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // int_lit
			nil,        // string_lit
			nil,        // id
			nil,        // (
			reduce(17), // ), reduce: FunctionCall
			reduce(17), // ,, reduce: FunctionCall
			nil,        // var
			nil,        // =
		},
	},
}
