// Code generated by gocc; DO NOT EDIT.

package parser

import (
	"github.com/aisk/goblin/ast"
)

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String:     `S' : Module	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Module : Statements	<< ast.NewModule(X[0]) >>`,
		Id:         "Module",
		NTType:     1,
		Index:      1,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewModule(X[0])
		},
	},
	ProdTabEntry{
		String:     `Statements : empty	<<  >>`,
		Id:         "Statements",
		NTType:     2,
		Index:      2,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String:     `Statements : StatementList	<<  >>`,
		Id:         "Statements",
		NTType:     2,
		Index:      3,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `StatementList : Statement	<< ast.NewStatementList(X[0]) >>`,
		Id:         "StatementList",
		NTType:     3,
		Index:      4,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewStatementList(X[0])
		},
	},
	ProdTabEntry{
		String:     `StatementList : StatementList Statement	<< ast.AppendStatementList(X[0], X[1]) >>`,
		Id:         "StatementList",
		NTType:     3,
		Index:      5,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendStatementList(X[0], X[1])
		},
	},
	ProdTabEntry{
		String:     `Statement : Expression	<<  >>`,
		Id:         "Statement",
		NTType:     4,
		Index:      6,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Statement : Declare	<<  >>`,
		Id:         "Statement",
		NTType:     4,
		Index:      7,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Statement : Assign	<<  >>`,
		Id:         "Statement",
		NTType:     4,
		Index:      8,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Statement : If	<<  >>`,
		Id:         "Statement",
		NTType:     4,
		Index:      9,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Statement : IfElse	<<  >>`,
		Id:         "Statement",
		NTType:     4,
		Index:      10,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Statement : While	<<  >>`,
		Id:         "Statement",
		NTType:     4,
		Index:      11,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Statement : Break	<<  >>`,
		Id:         "Statement",
		NTType:     4,
		Index:      12,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Statement : FunctionDefine	<<  >>`,
		Id:         "Statement",
		NTType:     4,
		Index:      13,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Statement : Return	<<  >>`,
		Id:         "Statement",
		NTType:     4,
		Index:      14,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `ExpressionList : Expression	<< ast.NewExpressionList(X[0]) >>`,
		Id:         "ExpressionList",
		NTType:     5,
		Index:      15,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewExpressionList(X[0])
		},
	},
	ProdTabEntry{
		String:     `ExpressionList : ExpressionList Expression	<< ast.AppendExpressionList(X[0], X[1]) >>`,
		Id:         "ExpressionList",
		NTType:     5,
		Index:      16,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendExpressionList(X[0], X[1])
		},
	},
	ProdTabEntry{
		String:     `Expression : Expression1	<<  >>`,
		Id:         "Expression",
		NTType:     6,
		Index:      17,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Expression1 : Expression2	<<  >>`,
		Id:         "Expression1",
		NTType:     7,
		Index:      18,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Expression1 : Expression1 "+" Expression2	<< ast.NewBinaryOperation(X[0], "+", X[2]) >>`,
		Id:         "Expression1",
		NTType:     7,
		Index:      19,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewBinaryOperation(X[0], "+", X[2])
		},
	},
	ProdTabEntry{
		String:     `Expression1 : Expression1 "-" Expression2	<< ast.NewBinaryOperation(X[0], "-", X[2]) >>`,
		Id:         "Expression1",
		NTType:     7,
		Index:      20,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewBinaryOperation(X[0], "-", X[2])
		},
	},
	ProdTabEntry{
		String:     `Expression2 : Expression3	<<  >>`,
		Id:         "Expression2",
		NTType:     8,
		Index:      21,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Expression2 : Expression2 "*" Expression3	<< ast.NewBinaryOperation(X[0], "*", X[2]) >>`,
		Id:         "Expression2",
		NTType:     8,
		Index:      22,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewBinaryOperation(X[0], "*", X[2])
		},
	},
	ProdTabEntry{
		String:     `Expression2 : Expression2 "/" Expression3	<< ast.NewBinaryOperation(X[0], "/", X[2]) >>`,
		Id:         "Expression2",
		NTType:     8,
		Index:      23,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewBinaryOperation(X[0], "/", X[2])
		},
	},
	ProdTabEntry{
		String:     `Expression3 : IntegerLiteral	<<  >>`,
		Id:         "Expression3",
		NTType:     9,
		Index:      24,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Expression3 : StringLiteral	<<  >>`,
		Id:         "Expression3",
		NTType:     9,
		Index:      25,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Expression3 : TrueLiteral	<<  >>`,
		Id:         "Expression3",
		NTType:     9,
		Index:      26,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Expression3 : FalseLiteral	<<  >>`,
		Id:         "Expression3",
		NTType:     9,
		Index:      27,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Expression3 : NilLiteral	<<  >>`,
		Id:         "Expression3",
		NTType:     9,
		Index:      28,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Expression3 : FunctionCall	<<  >>`,
		Id:         "Expression3",
		NTType:     9,
		Index:      29,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Expression3 : Identifier	<<  >>`,
		Id:         "Expression3",
		NTType:     9,
		Index:      30,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `Expression3 : "!" Expression3	<< ast.NewUnaryOperation("!", X[1]) >>`,
		Id:         "Expression3",
		NTType:     9,
		Index:      31,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewUnaryOperation("!", X[1])
		},
	},
	ProdTabEntry{
		String:     `Expression3 : "(" Expression ")"	<< X[1], nil >>`,
		Id:         "Expression3",
		NTType:     9,
		Index:      32,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[1], nil
		},
	},
	ProdTabEntry{
		String:     `Identifier : id	<< ast.NewIdentifier(X[0]) >>`,
		Id:         "Identifier",
		NTType:     10,
		Index:      33,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIdentifier(X[0])
		},
	},
	ProdTabEntry{
		String:     `IntegerLiteral : int_lit	<< ast.NewIntegerLiteral(X[0]) >>`,
		Id:         "IntegerLiteral",
		NTType:     11,
		Index:      34,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIntegerLiteral(X[0])
		},
	},
	ProdTabEntry{
		String:     `StringLiteral : string_lit	<< ast.NewStringLiteral(X[0]) >>`,
		Id:         "StringLiteral",
		NTType:     12,
		Index:      35,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewStringLiteral(X[0])
		},
	},
	ProdTabEntry{
		String:     `TrueLiteral : "true"	<< ast.NewTrueLiteral() >>`,
		Id:         "TrueLiteral",
		NTType:     13,
		Index:      36,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewTrueLiteral()
		},
	},
	ProdTabEntry{
		String:     `FalseLiteral : "false"	<< ast.NewFalseLiteral() >>`,
		Id:         "FalseLiteral",
		NTType:     14,
		Index:      37,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewFalseLiteral()
		},
	},
	ProdTabEntry{
		String:     `NilLiteral : "nil"	<< ast.NewNilLiteral() >>`,
		Id:         "NilLiteral",
		NTType:     15,
		Index:      38,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewNilLiteral()
		},
	},
	ProdTabEntry{
		String:     `FunctionCall : id "(" Arguments ")"	<< ast.NewFunctionCall(X[0], X[2]) >>`,
		Id:         "FunctionCall",
		NTType:     16,
		Index:      39,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewFunctionCall(X[0], X[2])
		},
	},
	ProdTabEntry{
		String:     `Arguments : empty	<<  >>`,
		Id:         "Arguments",
		NTType:     17,
		Index:      40,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String:     `Arguments : ArgumentList	<<  >>`,
		Id:         "Arguments",
		NTType:     17,
		Index:      41,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `ArgumentList : Expression	<< ast.NewExpressionList(X[0]) >>`,
		Id:         "ArgumentList",
		NTType:     18,
		Index:      42,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewExpressionList(X[0])
		},
	},
	ProdTabEntry{
		String:     `ArgumentList : ArgumentList "," Expression	<< ast.AppendExpressionList(X[0], X[2]) >>`,
		Id:         "ArgumentList",
		NTType:     18,
		Index:      43,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.AppendExpressionList(X[0], X[2])
		},
	},
	ProdTabEntry{
		String:     `Declare : "var" id "=" Expression	<< ast.NewDeclare(X[1], X[3]) >>`,
		Id:         "Declare",
		NTType:     19,
		Index:      44,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewDeclare(X[1], X[3])
		},
	},
	ProdTabEntry{
		String:     `Assign : id "=" Expression	<< ast.NewAssign(X[0], X[2]) >>`,
		Id:         "Assign",
		NTType:     20,
		Index:      45,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewAssign(X[0], X[2])
		},
	},
	ProdTabEntry{
		String:     `Block : "{" Statements "}"	<< X[1], nil >>`,
		Id:         "Block",
		NTType:     21,
		Index:      46,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[1], nil
		},
	},
	ProdTabEntry{
		String:     `Condition : Expression	<<  >>`,
		Id:         "Condition",
		NTType:     22,
		Index:      47,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String:     `If : "if" Condition Block	<< ast.NewIf(X[1], X[2], nil) >>`,
		Id:         "If",
		NTType:     23,
		Index:      48,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIf(X[1], X[2], nil)
		},
	},
	ProdTabEntry{
		String:     `IfElse : "if" Condition Block "else" Block	<< ast.NewIf(X[1], X[2], X[4]) >>`,
		Id:         "IfElse",
		NTType:     24,
		Index:      49,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIf(X[1], X[2], X[4])
		},
	},
	ProdTabEntry{
		String:     `IfElse : "if" Condition Block "else" If	<< ast.NewIf(X[1], X[2], X[4]) >>`,
		Id:         "IfElse",
		NTType:     24,
		Index:      50,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIf(X[1], X[2], X[4])
		},
	},
	ProdTabEntry{
		String:     `IfElse : "if" Condition Block "else" IfElse	<< ast.NewIf(X[1], X[2], X[4]) >>`,
		Id:         "IfElse",
		NTType:     24,
		Index:      51,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewIf(X[1], X[2], X[4])
		},
	},
	ProdTabEntry{
		String:     `While : "while" Condition Block	<< ast.NewWhile(X[1], X[2]) >>`,
		Id:         "While",
		NTType:     25,
		Index:      52,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewWhile(X[1], X[2])
		},
	},
	ProdTabEntry{
		String:     `Break : "break"	<< ast.NewBreak() >>`,
		Id:         "Break",
		NTType:     26,
		Index:      53,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewBreak()
		},
	},
	ProdTabEntry{
		String:     `FunctionDefine : "func" id "(" ")" Block	<< ast.NewFunctionDefine(X[1], X[4]) >>`,
		Id:         "FunctionDefine",
		NTType:     27,
		Index:      54,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewFunctionDefine(X[1], X[4])
		},
	},
	ProdTabEntry{
		String:     `Return : "return" Expression	<< ast.NewReturn(X[1]) >>`,
		Id:         "Return",
		NTType:     28,
		Index:      55,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.NewReturn(X[1])
		},
	},
}
