[book]
title = "Goblin Book"
description = "A concise introduction to the Goblin programming language"
authors = ["AN Long"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/aisk/goblin"
edit-url-template = "https://github.com/aisk/goblin/edit/master/docs/{path}"
site-url = "/goblin/"
